steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/orders-api',
      '.',
      '--build-arg',
      'PORT=${_PORT}',
      '--build-arg',
      'APP_SECRET=${_APP_SECRET}',
      '--build-arg',
      'RAVEN_CONFIG_URL=${_RAVEN_CONFIG_URL}',
      '--build-arg',
      'POSTGRES_HOST=${_POSTGRES_HOST}',
      '--build-arg',
      'POSTGRES_PORT=${_POSTGRES_HOST}',
      '--build-arg',
      'POSTGRES_USER=${_POSTGRES_USER}',
      '--build-arg',
      'POSTGRES_PASSWORD=${_POSTGRES_PASSWORD}',
      '--build-arg',
      'REDIS_HOST=${_REDIS_HOST}',
      '--build-arg',
      'REDIS_PORT=${_REDIS_PORT}',
      '--build-arg',
      'API_BASE_URL=${_API_BASE_URL}',
      '--build-arg',
      'GC_CREDENTIALS=${_GC_CREDENTIALS}',
      '--build-arg',
      'GC_BUCKET_NAME=${_GC_BUCKET_NAME}',
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/orders-api']

  #step 3
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west6-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=staging'

options:
  substitution_option: 'ALLOW_LOOSE'
