apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  namespace: staging
  labels:
    app: orders-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: gcr.io/palgrow/orders-api:latest
          ports:
            - containerPort: 80
