apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders-api
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337
  selector:
    app: orders-api
  type: LoadBalancer
